name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Variables
        run: vercel pull --yes --evironment=production --token=${{secrets.VERCEL_TOKEN}}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuild --prod --token=${{secrets.VERCEL_TOKEN}}